import images1 from "./images/images1.jpg";
import images2 from "./images/images2.jpg";
import images3 from "./images/images3.jpg";
import images4 from "./images/images4.jpg";
import images5 from "./images/images5.jpg";

const imagesData = [
  {
    id: 0,
    url: images1,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
    created_at: "2021-10-21T20:36:51Z",
  },
  {
    id: 1,
    url: images2,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 2,
    url: images2,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 3,
    url: images3,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 4,
    url: images4,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 5,
    url: images5,

    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    lilkes: 278,
  },
  {
    id: 0,
    url: images1,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
    created_at: "2021-10-21T20:36:51Z",
  },
  {
    id: 1,
    url: images2,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 2,
    url: images2,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 3,
    url: images3,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 4,
    url: images4,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 5,
    url: images5,

    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    lilkes: 278,
  },
  {
    id: 0,
    url: images1,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
    created_at: "2021-10-21T20:36:51Z",
  },
  {
    id: 1,
    url: images2,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 2,
    url: images2,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 3,
    url: images3,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 4,
    url: images4,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 5,
    url: images5,

    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    lilkes: 278,
  },
  {
    id: 0,
    url: images1,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
    created_at: "2021-10-21T20:36:51Z",
  },
  {
    id: 1,
    url: images2,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 2,
    url: images2,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 3,
    url: images3,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 4,
    url: images4,
    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    likes: 278,
  },
  {
    id: 5,
    url: images5,

    aperture: "3.2",
    exposure_time: "1/400",
    focal_length: "35.0",
    iso: 400,
    make: "Canon",
    model: " EOS 6D Mark II",
    name: "Canon, EOS 6D Mark II",
    alt_description: "a large cloud is in the sky over the ocean",
    instagram_username: "@Bajirao1292",
    views: 2470,
    lilkes: 278,
  },
];

export default imagesData;
